title: IdMux Proxy
description: A small and secure proxy for more than one IdP session.
url: https://4nass.github.io
baseurl: /idmux-proxy
theme: jekyll-theme-minimal
markdown: kramdown
show_downloads: false
defaults:
  - scope:
      path: ""
    values:
      layout: default
exclude:
  - architecture.md
  - configuration.md
  - contributing.md
  - development.md
  - editing.md
  - getting-started.md
  - devops-and-operations.md
  - operations.md
  - security-invariants.md
